### ISSUE TITLE
Why abandond this project?

### ISSUE THREAD

**Issue by Zaid-maker** [syko9000/uTorrent-WebUI-Mobile#2]
hi, why this project is not update since 9 years?

**Comment by syko9000** [comment]
Honestly, I forgot I made this, I haven't used uTorrent in more than half that time.

**Comment by Zaid-maker** [comment]
> Honestly, I forgot I made this, I haven't used uTorrent in more than half that time.

Damn! you have now any plan on this to bring back?

**Comment by syko9000** [comment]
I just spun up a docker container of a ekho/utorrent:latest and mounted this "mobile" folder to /utorrent/webui/ng/webui/mobile and then went to http://localhost:8080/gui/mobile/index.html and this thing mostly still works amazingly. The API calls are fine but the UI disappears from time to time needing a page refresh. jQuery Mobile was deprecated a couple years ago... so it really needs rewritten from the ground up, many better technologies these days.

**Comment by Zaid-maker** [comment]
> I just spun up a docker container of a ekho/utorrent:latest and mounted this "mobile" folder to /utorrent/webui/ng/webui/mobile and then went to http://localhost:8080/gui/mobile/index.html and this thing mostly still works amazingly. The API calls are fine but the UI disappears from time to time needing a page refresh. jQuery Mobile was deprecated a couple years ago... so it really needs rewritten from the ground up, many better technologies these days.

Ohhh wow that's impressive that a code written 9 years ago still works! Sorry i have disabled email notifications

**Comment by Zaid-maker** [comment]
Can u host this project on github pages? as its a html project i guess it should works ust fine
